<?php
    /** @var Magento\Framework\View\Element\Template $block */
    /** @var Macademy\Blog\ViewModel\Post $postVm */
    /** @var \Magento\Framework\Escaper $escaper */

    $postVm = $block->getData('post_vm');
    $post = $postVm->getDetail();

?>



<div class="blog-post-detail">
    <h1> <?= $post->getTitle();  ?></h1>
    <p><em> <?= __('Created at: %1',$post->getCreateAt()) ?> </em></p>
    <p><?= $escaper->escapeHtml($post->getContent(),['em','p','strong']);?></p>
</div>


